language: python

services:
  – mysql

python:
  - "2.7.8"

before_install:
  - export MARK2CURE_SECRET_KEY=‘foo’
  - export MARK2CURE_ADMIN_PASSWORD=‘foo’

  - export MARK2CURE_MANDRILL_API_KEY=‘foo’
  - export MARK2CURE_ENTREZ_EMAIL=‘foo’
  - export MARK2CURE_BROKER_URL='amqp://'

  - export MARK2CURE_AWS_ACCESS_KEY_ID=‘foo’
  - export MARK2CURE_AWS_SECRET_ACCESS_KEY=‘foo’

  - export MARK2CURE_SENTRY_PUBLIC_KEY=‘foo’
  - export MARK2CURE_SENTRY_PRIVATE_KEY=‘foo’
  - export MARK2CURE_SENTRY_PROJECT_ID=‘foo’
  - export MARK2CURE_SENTRY_DSN=‘foo’
  - export MARK2CURE_DATABASE_URL=‘foo’
  - secure: "X8Dl8KCvl+HVRIcyWbkbJ+6vQPTT+V/epjnmkSqY/b2cQGaHYc1Ebl6o4txsfqLm6jI1R/DbBxw91eQqdzWIBr0lHwxyk49yXlbd6t7Bhz8bjUjaBBJu16qEDmWOXkeYGwm/Yx8TD4mMNusn9Lhex9A2HF2oeGhI6YwBZ3bqpKm7bXXNk91d9GXxM25QtR23rDqMsF+sDGCbCRcNfAZN8w5l3B5T3HgZOl1ivXIKyQSbA6C9ZMqStf8YZRp7qqH/spz4o4Zw/qq5PDpp4kNsrczrDIFcsoRF+sVpWN/XUjnhEe6yRxvc6RXYCKAMtae6SEp67A309DJyrKBWYY9a247bLlYGSnp1yr4tHzbERUp6FTBC92YeENRyVoGrI5AW6SXOcuq0L4bI/q5A8CeIG00XUEjXzgd5cvLa2rfGiVfYhbh3jK44TVNJeCudxYpkJ6fV2PNtqoeR9TMxzBRTpXAoerT+5rCSoom9bSvT+G959FCpKUQlpqysu7RPAAU13fcTKEDnxYUYWWM2lhHEhgR0DaXFmMkb3nu+zAnfqMuJQhiPQnclisHtlTaMX6FCFrMu/JTfPNQP69C895PSPKAgmBEKwPnvLig+GH260XxiKkviXxhlmnT/9NJD3WBxjzUMC2XSz6PJ4nHgCoQ0zX0zuaYEx5DfeCsbSwb2Bho="

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
